export const UPDATE_MODULE = 'app/UPDATE_MODULE';
export const UPDATE_ACCESSMENU = 'app/UPDATE_ACCESSMENU';
export const LOGIN_SUCCESS = 'user/LOGIN_SUCCESS';
export const GET_USERINFO_SUCCESS = 'user/GET_USERINFO_SUCCESS';
export const LOGOUT_SUCCESS = 'user/LOGOUT_SUCCESS';
