// export const NAVSIDE_SUCCESS = 'navSide/NAVSIDE_SUCCESS'
// export const ERROR_MSG = 'navSide/ERROR_MSG'
// export const GETNAVSIDELISTS = 'navSide/GETNAVSIDELISTS'
// export const ISFETCHING = 'navSide/ISFETCHING'
// export const CHANGE_STATES = 'navSide/CHANGE_STATES'
