module.exports = {
  User: {
    isAdmin: '',
    email: '',
    userPermission: [],
    moduleId: 0,
    userRole: [],
    userName: '',
    nickName: '',
    inviteCode: '',
    captcha: '',
    prefix: '',
    pwd: '',
    phone: '',
    type: '',
    notification: [],
    avatar: '',
    desc: '',
    title: '',
  },
  Function: {
    name: '',
    code: '',
    description: '',
    moduleId: '',
    module: '',
    id: '',
  },
  Menu: {
    functionCode: '',
    icon: '',
    id: '',
    leftMenu: true,
    isLock: false,
    name: '',
    parentId: '',
    parentName: '',
    path: '',
    sort: '',
    title: '',
  },
  Department: {
    icon: '',
    id: '',
    code: '',
    leftDepartment: true,
    isLock: false,
    name: '',
    parentId: '',
    parentName: '',
    path: '',
    sort: '',
    title: '',
    userId: [],
    roleId: [],
    level: '',
  },
  Role: {
    name: '',
    code: '',
    moduleId: '',
    description: '',
    id: '',
    permission: [],
    userId: [],
    departmentId: '',
  },
};
